# .github/workflows/R-CMD-check.yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - uses: codecov/codecov-action@v4.0.1
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check
      # - uses: r-lib/actions/check-r-package@v2

      - name: Test coverage
        run: |
          install.packages("covr", repos = "https://cloud.r-project.org")
          covr::codecov()
        shell: Rscript {0}

# - name: Upload coverage reports to Codecov
# - yes
