# .github/workflows/R-CMD-check.yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: code-cov

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
         with:
          extra-packages: any::covr

      - uses: codecov/codecov-action@v4.0.1
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check
      # - uses: r-lib/actions/check-r-package@v2

      - name: Test coverage
         run: covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))
        # run: |
        #   install.packages("covr", repos = "https://cloud.r-project.org")
        #   covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))
        shell: Rscript {0}

# - name: Upload coverage reports to Codecov
# - yes
